// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBgsjy5xEP5XGEMpZw8_eTudYcbk6KI_E',
    appId: '1:950271157769:web:9dd004d95d72bd55b43ad8',
    messagingSenderId: '950271157769',
    projectId: 'attendance-management-sy-e7aab',
    authDomain: 'attendance-management-sy-e7aab.firebaseapp.com',
    storageBucket: 'attendance-management-sy-e7aab.appspot.com',
    measurementId: 'G-75VX3WTBH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEwddqur_3Q3Bqh8wUaZQVEMr88thMbs',
    appId: '1:950271157769:android:fdd4a08cd7fcdbf6b43ad8',
    messagingSenderId: '950271157769',
    projectId: 'attendance-management-sy-e7aab',
    storageBucket: 'attendance-management-sy-e7aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuhT-aVJhEJiceZbigRFEoNXdcENt32SA',
    appId: '1:950271157769:ios:b69039da3f3f37b3b43ad8',
    messagingSenderId: '950271157769',
    projectId: 'attendance-management-sy-e7aab',
    storageBucket: 'attendance-management-sy-e7aab.appspot.com',
    iosBundleId: 'com.example.attendanceMangementSystem',
  );
}
